### ISSUE TITLE
Vertical gaps in the graph lines

### ISSUE THREAD

**Issue by ghost** [cjbassi/ytop#54]
- Arch / [`ytop-git`<sup>AUR</sup>](https://aur.archlinux.org/packages/ytop-git/)
- `❯ ytop -V`: ytop 0.5.1
- Terminal: [`kitty`](https://www.archlinux.org/packages/community/x86_64/kitty/)

I noticed that graphs don't look good on my main machine.

- Here's how it rendered on an old VM (also using Arch and [`kitty`](https://www.archlinux.org/packages/community/x86_64/kitty/)):
![vm](https://user-images.githubusercontent.com/59181811/77676639-df437280-6f8e-11ea-80f6-08b6857be1c0.png)

- Here's how it renders on my main machine:
![main](https://user-images.githubusercontent.com/59181811/77676635-de124580-6f8e-11ea-9c4e-27c852d81591.png)

The dots characters look way too thin. They should look just like on the README screenshot and the VM screenshot.

`kitty.conf`:

```
font_family                   JetBrainsMonoMedium Nerd Font
font_size                     10.5
bold_font                     auto
italic_font                   auto
bold_italic_font              auto
force_ltr                     no
adjust_line_height            0
adjust_column_width           0
disable_ligatures             cursor
font_features                 none
box_drawing_scale             0.001, 1, 1.5, 2

```

`.Xresources`:

```
Xft.dpi: 96
Xft.antialias: true
Xft.hinting: true
Xft.rgba: rgb
Xft.autohint: false
Xft.hintstyle: hintfull
Xft.lcdfilter: lcddefault
```

`.xinitrc`:

```
xrdb -load ~/.config/X11/.Xresources
```

I tried using another font with [`kitty`](https://www.archlinux.org/packages/community/x86_64/kitty/) (Fira Code Nerd Font Mono) but it doesn't make any difference.

Any idea which settings I should tweak in order to get the same rendering than the VM one?

Thanks.

**Comment by cjbassi** [comment]
I think this is a duplicate of #40. There is a fix in the works that should be available soon.

**Comment by ghost** [comment]
> I think this is a duplicate of #40. There is a fix in the works that should be available soon.

Well, I'm not so sure. #40 was opened on February 14th and my virtual machine screenshot (where the graph looks decent) was taken on March 4th. I remember I was using [`ytop-bin`<sup>AUR</sup>](https://aur.archlinux.org/packages/ytop-bin/) at that time.

I tried [`gotop-bin` <sup>AUR</sup>](https://aur.archlinux.org/packages/gotop-bin/).
- How graph renders on [`gotop` GitHub page](https://github.com/xxxserxxx/gotop/):
![gotop-gif](https://github.com/cjbassi/ytop/raw/master/assets/demos/demo.gif)

- How [`gotop-bin` <sup>AUR</sup>](https://aur.archlinux.org/packages/gotop-bin/) graph renders on my machine:
![2020-03-26_21-04-42](https://user-images.githubusercontent.com/59181811/77691703-ae226c80-6fa5-11ea-8a31-d41fc737dc80.gif)

As you can see, while the spacing looks better indeed, the dots characters are still abnormally thin.

This and the fact that `ytop` was rendering the graphs as expected on my VM twenty days ago makes me think it's rather an issue with my own settings, but I don't know what it could be.

**Comment by cjbassi** [comment]
Oh interesting, so there's a bunch of vertical gaps in the graphs. I'm not sure what that could be, although I'm also thinking it's probably something to do with your setup.

**Comment by cjbassi** [comment]
So it seems like there is extra vertical spacing between the braille characters that shouldn't be there. This is probably a font or terminal issue. If you look at the CPU percents, there is also vertical spacing between the characters but that seems appropriate whereas for the braille characters it is not.

**Comment by ghost** [comment]
Ok, it looks like there's something wrong with my `kitty` config, most likely the fonts section.

Left: `kitty` | Right: `alacritty`
![2020-03-26_22-10-30](https://user-images.githubusercontent.com/59181811/77697632-846e4300-6faf-11ea-9014-93a01210237a.gif)

No issue with graph using `alacritty`.

Here's my `alacritty.yml`:

```
env:
  TERM: xterm-256color

window:
  dimensions:
     columns: 85
     lines: 24

  padding:
    x: 10
    y: 10

  dynamic_padding: true

  cursor:
  style: Beam

live_config_reload: true
draw_bold_text_with_bright_colors: false
background_opacity: 1.00

font:
  normal:
    family: JetBrainsMonoMedium Nerd Font
    style: Regular
    size: 10

  bold:
    family: JetBrainsMonoMedium Nerd Font
    style: Bold
    size: 10

  italic:
    family: JetBrainsMonoMedium Nerd Font
    style: Italic
    size: 10

  bold_italic:
    family: JetBrainsMonoMedium Nerd Font
    style: Bold Italic
    size: 10
```

Changing the font family to `JetBrainsMono Nerd Font` doesn't break anything, it looks the same.

I'm going to do further testing and see if I can get equivalent rendering with `kitty`.

Cheers!
